# https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix
# => run: docker version để biết enginer version bao nhiêu
# version: "3.9" 
# build context: chỉ vị trí của file Dockerfile 
services:
  nginx:
    container_name: my-nginx
    depends_on:
      - backend
    restart: always # because it is routing traffic to our entire app
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8001:80
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      #- ./fe-react-meeting/dist/:/usr/share/nginx/html/

  backend:
    container_name: my-backend
    build:
      context: ./backend-nest-js-meeting
    restart: unless-stopped
    environment:
      - PORT=8000
      #- NODE_ENV=production
      #- MONGO_URL=mongodb+srv://sontx13:Sonphuong1710@cluster0.bp5irmg.mongodb.net/nestjs_db
      # MONGO_URL=mongodb://root:123456@db-mongo:27017/sontx13?authSource=admin
      # - DB_HOST=host.docker.internal
    ports:
      - 8000:8000

  # docker compose -p sontx-meeting up -d
